sudo: required
services: 
  - docker

before_install:
  - docker build -t luciancochior/frontend-react -f Dockerfile.dev .

script:
  - docker run -e CI=true luciancochior/frontend-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-302686857952"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"